
export const GET_CHARACTERS_START = "GET_CHARACTERS_START"
export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS"
export const GET_CHARACTERS_FAILED = "GET_CHARACTERS_FAILED"

export const FILTERED_RESULT_START = "FILTERED_RESULT_START"
export const FILTERED_RESULT_SUCCESS = "FILTERED_RESULT_SUCCESS"
export const FILTERED_RESULT_FAIL = "FILTERED_RESULT_FAIL"
